"""empty message

Revision ID: cee2e5d3df32
Revises: e69214d1f434
Create Date: 2021-12-17 10:27:12.808107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee2e5d3df32'
down_revision = 'e69214d1f434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_interview',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interview_id')
    )
    op.drop_table('interviewers_user')
    op.drop_table('interviewers_interview')
    op.drop_table('interviewer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewers_interview',
    sa.Column('interviewer_id', sa.INTEGER(), nullable=False),
    sa.Column('interview_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('interviewer_id', 'interview_id')
    )
    op.create_table('interviewers_user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('interviewer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interviewer_id')
    )
    op.drop_table('users_interview')
    # ### end Alembic commands ###
