# Generated by Django 3.2.9 on 2021-12-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
